on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment

jobs:
  test:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: echo $NAME
